import { Month } from "../../models/Month"
import * as MonthHelpers from "../../models/Month"

describe("Month", () => {
  it("Parses Month number correctly", () => {
    expect(MonthHelpers.parseNumber(0)).toEqual(Month.January)
    expect(MonthHelpers.parseNumber(1)).toEqual(Month.February)
    expect(MonthHelpers.parseNumber(2)).toEqual(Month.March)
    expect(MonthHelpers.parseNumber(3)).toEqual(Month.April)
    expect(MonthHelpers.parseNumber(4)).toEqual(Month.May)
    expect(MonthHelpers.parseNumber(5)).toEqual(Month.June)
    expect(MonthHelpers.parseNumber(6)).toEqual(Month.July)
    expect(MonthHelpers.parseNumber(7)).toEqual(Month.August)
    expect(MonthHelpers.parseNumber(8)).toEqual(Month.September)
    expect(MonthHelpers.parseNumber(9)).toEqual(Month.October)
    expect(MonthHelpers.parseNumber(10)).toEqual(Month.November)
    expect(MonthHelpers.parseNumber(11)).toEqual(Month.December)
  })

  it("Throws error on invalid month number", () => {
    expect(() => MonthHelpers.parseNumber(-1)).toThrow()
    expect(() => MonthHelpers.parseNumber(12)).toThrow()
  })

  it("Parses Month string correctly", () => {
    expect(MonthHelpers.parse("0")).toEqual(Month.January)
    expect(MonthHelpers.parse("00")).toEqual(Month.January)
    expect(MonthHelpers.parse("1")).toEqual(Month.February)
    expect(MonthHelpers.parse("01")).toEqual(Month.February)
    expect(MonthHelpers.parse("2")).toEqual(Month.March)
    expect(MonthHelpers.parse("02")).toEqual(Month.March)
    expect(MonthHelpers.parse("3")).toEqual(Month.April)
    expect(MonthHelpers.parse("03")).toEqual(Month.April)
    expect(MonthHelpers.parse("4")).toEqual(Month.May)
    expect(MonthHelpers.parse("04")).toEqual(Month.May)
    expect(MonthHelpers.parse("5")).toEqual(Month.June)
    expect(MonthHelpers.parse("05")).toEqual(Month.June)
    expect(MonthHelpers.parse("6")).toEqual(Month.July)
    expect(MonthHelpers.parse("06")).toEqual(Month.July)
    expect(MonthHelpers.parse("7")).toEqual(Month.August)
    expect(MonthHelpers.parse("07")).toEqual(Month.August)
    expect(MonthHelpers.parse("8")).toEqual(Month.September)
    expect(MonthHelpers.parse("08")).toEqual(Month.September)
    expect(MonthHelpers.parse("9")).toEqual(Month.October)
    expect(MonthHelpers.parse("09")).toEqual(Month.October)
    expect(MonthHelpers.parse("10")).toEqual(Month.November)
    expect(MonthHelpers.parse("11")).toEqual(Month.December)
  })

  it("Throws error on invalid month string", () => {
    expect(() => MonthHelpers.parse("-1")).toThrow()
    expect(() => MonthHelpers.parse("12")).toThrow()
    expect(() => MonthHelpers.parse("abc")).toThrow()
    expect(() => MonthHelpers.parse("")).toThrow()
  })

  it("Generates correct string", () => {
    expect(MonthHelpers.toJSON(Month.January)).toEqual("0")
    expect(MonthHelpers.toJSON(Month.February)).toEqual("1")
    expect(MonthHelpers.toJSON(Month.March)).toEqual("2")
    expect(MonthHelpers.toJSON(Month.April)).toEqual("3")
    expect(MonthHelpers.toJSON(Month.May)).toEqual("4")
    expect(MonthHelpers.toJSON(Month.June)).toEqual("5")
    expect(MonthHelpers.toJSON(Month.July)).toEqual("6")
    expect(MonthHelpers.toJSON(Month.August)).toEqual("7")
    expect(MonthHelpers.toJSON(Month.September)).toEqual("8")
    expect(MonthHelpers.toJSON(Month.October)).toEqual("9")
    expect(MonthHelpers.toJSON(Month.November)).toEqual("10")
    expect(MonthHelpers.toJSON(Month.December)).toEqual("11")
  })
})
